
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from msilib.schema import ListBox
from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import StringVar, Tk, Canvas, Entry, Listbox, Button, PhotoImage, Label


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\Users\20221041110019\Documents\python\projeto-final-Peoo\listagem\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("350x450")
window.configure(bg = "#343034")
window.title("listagem")

num = StringVar()
lista = Listbox(window)

global insert 
insert = 1

def inserir():
    lista.insert(insert, num.get())
    print(lista)

    global insert
    insert+=1

canvas = Canvas(
    window,
    bg = "#343034",
    height = 450,
    width = 350,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    23.0,
    54.0,
    anchor="nw",
    text="Inserir número:",
    fill="#FFFFFF",
    font=("Inter", 18 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    220.0,
    67.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    textvariable=insert
)
entry_1.place(
    x=159.0,
    y=59.0,
    width=122.0,
    height=15.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))

button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=inserir(),
    relief="flat"
)
button_1.place(
    x=288.0,
    y=60.0,
    width=44.0,
    height=16.0
)

canvas.create_rectangle(
    23.0,
    103.0,
    325.0,
    364.0,
    fill="#D9D9D9",
    outline="")

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    173.5,
    125.5,
    image=entry_image_2
)
entry_2 = Label(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    textvariable=lista
)
entry_2.place(
    x=33.0,
    y=117.0,
    width=281.0,
    height=15.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=73.0,
    y=384.0,
    width=22.0,
    height=22.0
)

canvas.create_text(
    101.0,
    389.0,
    anchor="nw",
    text="Menor",
    fill="#FFFFFF",
    font=("Inter", 10 * -1)
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=146.0,
    y=384.0,
    width=22.0,
    height=22.0
)

canvas.create_text(
    174.0,
    389.0,
    anchor="nw",
    text="Maior",
    fill="#FFFFFF",
    font=("Inter", 10 * -1)
)

canvas.create_text(
    240.0,
    389.0,
    anchor="nw",
    text="Maior",
    fill="#FFFFFF",
    font=("Inter", 10 * -1)
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=212.0,
    y=384.0,
    width=22.0,
    height=22.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: inserir(),
    relief="flat"
)
button_5.place(
    x=141.0,
    y=417.0,
    width=56.0,
    height=17.0
)
window.resizable(False, False)
window.mainloop()
